apiVersion: v2
actions:
  - name: Run locust
    events:
      - name: sh.keptn.event.test.triggered
        jsonpath:
          property: $.data.test.teststrategy
          match: performance
    tasks:
      - name: Run locust smoke tests
        files:
          - locust/load.py
          - locust/locust.config
        env:
          - name: DEPLOYMENTURL
            value: "$.data.deployment.deploymentURIsPublic 0"
            valueFrom: event          
        image: locustio/locust
        cmd:
          - locust
        args:
          - '--headless'
          - '--host=$(DEPLOYMENTURL)'
          - '-f=/keptn/locust/load.py'
          - '--config=/keptn/locust/locust.config'
