apiVersion: v2
actions:
  - name: Run locust
    events:
      - name: sh.keptn.event.test.triggered
        jsonpath:
          property: $.data.test.teststrategy
          match: performance
    tasks:
      - name: Run locust smoke tests
        files:
          - locust/load.py
          - locust/locust.conf
        image: locustio/locust:2.8.4
        cmd:
          - locust
        args:
          - '--headless'
          - '--host'
          - 'http://tnt-aapl-svc.delivery-demo-staging.34.217.41.88.nip.io:80/'
          - '--locustfile'
          - '/keptn/locust/load.py'
          - '--config'
          - '/keptn/locust/locust.conf'
